//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActorsAndProducer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActorsAndProducer()
        {
            this.CastInMovies = new HashSet<CastInMovie>();
            this.Movies = new HashSet<Movy>();
        }
    
        public int ActorOrProducerId { get; set; }
        public string Name { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<bool> IsActor { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string BIO { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CastInMovie> CastInMovies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movy> Movies { get; set; }
    }
}
