//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class CastInMovie
    {
        public int CMID { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<int> ActorId { get; set; }
    
        public virtual ActorsAndProducer ActorsAndProducer { get; set; }
        public virtual Movy Movy { get; set; }
    }
}
