//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMDB.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movy()
        {
            this.CastInMovies = new HashSet<CastInMovie>();
        }
    
        public int MovieId { get; set; }
        public string Name { get; set; }
        public Nullable<int> YearOfRelease { get; set; }
        public Nullable<int> ProducerId { get; set; }
        public string Poster { get; set; }
        public string Plot { get; set; }
    
        public virtual ActorsAndProducer ActorsAndProducer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CastInMovie> CastInMovies { get; set; }
    }
}
